### ISSUE TITLE
Issues running on cluster2

### ISSUE THREAD

**Issue by mariesaitou** [MeHelmy/princess#10]
Dear Medhat,

Thank you very much for your constant help.
Princess worked fine once, but now, previously worked Princess pipeline stopped working on our server.
I really appreciate your help with this. 

This is what I have done so far:

(1) Ran previously worked pipeline (May) recently but got an error (August)
(2) Re-installed the newest Princess and replaced default .yml files with the one for our environment
(3) Got the same error

[This is what we used to get](https://github.com/MeHelmy/princess/files/7189277/LLsal.420.log)
[This is what we now get:snakemake.log](https://github.com/MeHelmy/princess/files/7189280/2021-08-04T212941.431075.snakemake.log)
[This is what we now get:general.log](https://github.com/MeHelmy/princess/files/7189281/tanner.84.log)
[The script](https://github.com/MeHelmy/princess/files/7189284/pri.tanner.0504-e.slurm.txt)

Thank you very much!!!

**Comment by MeHelmy** [comment]
Thank you for reaching, 
Can you please share the content of file  /net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/snp/minimap/chrsplit/data.split.ssa01-23_2.log from 

Thanks,
Medhat

**Comment by mariesaitou** [comment]
Hi, tHank you very much!!! 

It says:

Traceback (most recent call last):
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/../clair.py", line 92, in <module>
    main()
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/../clair.py", line 79, in main
    submodule = import_module("%s.%s" % (directory, submodule_name))
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/call_var.py", line 15, in <module>
    from clair.model import Clair
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/model.py", line 20, in <module>
    import clair.selu as selu
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/selu.py", line 11, in <module>
    from tensorflow.contrib import layers
ModuleNotFoundError: No module named 'tensorflow.contrib'
Traceback (most recent call last):
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/../clair.py", line 92, in <module>
    main()
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/../clair.py", line 86, in main
    submodule.main()
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/dataPrepScripts/CreateTensor.py", line 440, in main
    OutputAlnTensor(args)
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/dataPrepScripts/CreateTensor.py", line 372, in OutputAlnTensor
    tensor_fp.stdin.write(l)
BrokenPipeError: [Errno 32] Broken pipe
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
Traceback (most recent call last):
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/../clair.py", line 92, in <module>
    main()
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/clair/../clair.py", line 86, in main
    submodule.main()
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/dataPrepScripts/ExtractVariantCandidates.py", line 450, in main
    make_candidates(args)
  File "/net/cn-1/mnt/SCRATCH/princesstest/result84/tanner/.snakemake/conda/e09f93bd/bin/dataPrepScripts/ExtractVariantCandidates.py", line 367, in make_candidates
    can_fp.stdin.write(output)
BrokenPipeError: [Errno 32] Broken pipe
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1

**Comment by MeHelmy** [comment]
Thank you for your patience, 
Looking at the error `ModuleNotFoundError: No module named 'tensorflow.contrib'` looks like Princess was not installed properly. You may first try `pip install tensorflow==1.13.1`; if it did not work, you need to reinstall Princess.

Thanks,
Medhat

**Comment by mariesaitou** [comment]
I see... in the previous time, another package was missing and I reinstalled it. Something wired may be repetitively happening at the installation. I'll try the reinstallation again and will see what will be happening. Thank you very much.

**Comment by MeHelmy** [comment]
Thank you Mari,
Honestly, I do not know what is happening in your cluster or working system, but these missing libraries are not normal, special that  I install my files through Conda implicitly, is you remember also at some point the bam files were deleted while running.

I will leave the issue here opened, so I can follow up with you.

Best,
Medhat

**Comment by MeHelmy** [comment]
Hi,
Please let me know If you still see the issue. Otherwise, I will count it as solved, and I will close it.
Best,
Medhat

**Comment by mariesaitou** [comment]
Thank you very much, I have currently no time to explore it so please close
it for now.

**Comment by mariesaitou** [comment]
It has been running for 20 days. Too weird so I will start it over again.
